### ISSUE TITLE
Publish to Maven central

### ISSUE THREAD

**Issue by rmichela** [linkerd/linkerd-zipkin#17]

**Comment by rmichela** [comment]
According to Maven Central, version 0.0.1 of `linkerd-zipkin_2.12` was published, not version 1.3.3, as the PR would indicate. Is this correct? @hawkw 

https://search.maven.org/#search%7Cga%7C1%7Clinkerd-zipkin_2.12

**Comment by hawkw** [comment]
Hi @rmichela, yes, that's correct; the `linkerd-zipkin` artefact is versioned 0.0.1, but it corresponds to Linkerd version 1.3.3. In the future, `linkerd-zipkin` artefacts will share version numbers with the Linkerd versions they are compatible with.
