### ISSUE TITLE
Add Tags to Tracing

### ISSUE THREAD

**Issue by carlislk** [linkerd/linkerd-zipkin#27]
Trying to add additional tags in traces sent using this module. Would like to send host ip as well as potentially other tags. Is this supported?

**Comment by klingerf** [comment]
Hey @carlislk, thanks for opening an issue. It shouldn't be a problem to add additional annotations, but you'd need to make that change in the [linkerd](https://github.com/linkerd/linkerd) repo itself. This repo just handles transport for the tracing data, once it has been produced by linkerd.

**Comment by carlislk** [comment]
Hello @klingerf thanks for the quick response. Okay will do.
