### ISSUE TITLE
Release for linkerd 1.5.0

### ISSUE THREAD

**Issue by negz** [linkerd/linkerd-zipkin#33]
I'd like to try out linkerd 1.5.0, but I use this plugin. I attempted to upgrade the plugin to Finagle 18.9.1, but doing so seems to require upgrading to `io.zipkin.finagle2`, which I don't currently have the bandwidth to figure out.

**Comment by dadjeibaah** [comment]
Update: We are currently to hear back from the zipkin finagle team to publish the latest `io.zipkin.finagle2` artifacts so we can update linkerd-zipkin

**Comment by negz** [comment]
Thanks! I ran into the same issue when I had a quick pass at doing this myself. FWIW this isn't high urgency for us.

**Comment by dadjeibaah** [comment]
Maven artifacts have been published for Linkerd-zipkin 1.5.0 and repo has been update based on #34. Closing this issue.

**Comment by negz** [comment]
Thanks @dadjeibaah!
