### ISSUE TITLE
JAR uploaded to maven central does not include all dependencies

### ISSUE THREAD

**Issue by juzsal** [linkerd/linkerd-zipkin#47]
The JAR in maven central only seems to include the code from this repo, and does not have its dependencies bundled. This means that we have to build from source ourselves if we want to use this plugin. Is this intentional?

**Comment by cpretzer** [comment]
@jlsalmon I believe this is done to keep the size of the jar in maven central small.

The plugin is meant to run as part of a Linkerd installation. Are you planning to use it outside of Linkerd?
